### ISSUE TITLE
Import codes from CSV

### ISSUE THREAD

**Issue by avdi** [rubyrogues/ppwm-matcher#2]
Let me import a list of codes from CSV. Limit the codes that can be matched to the ones that already exist.

BTW, anyone know how to make such an import script work on Heroku?

**Comment by rwjblue** [comment]
I'll try to take a stab at this, but could you gist an example of the CSV that you would like to use?

**Comment by avdi** [comment]
```
ABC123
DEF456
CBA789
...
```

That's all there is to it :-) It should be idempotent, i.e. it should never make a new record for an existing code. That's about the only extra consideration I can think of.

**Comment by avdi** [comment]
(So yeah, "CSV" is probably the wrong term. "One code per line" would be more accurate.)

**Comment by rwjblue** [comment]
Gotcha, makes sense.  I am assuming that you will provide an even number of codes. Is that correct?

**Comment by avdi** [comment]
Nope. Two people share one code.

**Comment by avdi** [comment]
...I just realized that this is not how it currently works. Crap. I do not have time to print up new sheets :-/

**Comment by rwjblue** [comment]
OK, then the current schema would need to be changed (unless I am totally missing something here)...

**Comment by rwjblue** [comment]
@avdi No worries, we can make it work!

**Comment by avdi** [comment]
Added #3

**Comment by rwjblue** [comment]
OK, so you can do a bulk import now by posting to '/code/import' (see [here](https://github.com/rubyrogues/ppwm-matcher/blob/master/spec/app_spec.rb#L11)) .  

I'll put together an update to the README giving an example in `Net::HTTP`.

**Comment by bf4** [comment]
Can we close this issue, now?

**Comment by rwjblue** [comment]
Works for me. I'll update here once the README is updated...

**Comment by joonty** [comment]
Are you guys worried about the security implications of the POST? I know that the only thing someone could do is add codes, but since this is open source it might be a good idea to put some basic authentication around it.

**Comment by rwjblue** [comment]
Absolutely, we added another issue to add authorization to all of the actions. 

I should have it implemented this morning. 

Robert Jackson

-- twitter: rwjblue
-- github: rjackson

**Comment by joonty** [comment]
Ah, gotcha.

Would the idea also be to only allow a certain set of users for that particular action? Or maybe just avdi?

I'm happy to implement the authorization block, if you're not already working on it.

**Comment by rwjblue** [comment]
Yeah, I think the thought was to restrict creation by  adding a boolean field to the User model, then make sure @avdi's user is seeded properly. 

Robert Jackson

-- twitter: rwjblue
-- github: rjackson

**Comment by rwjblue** [comment]
@joonty - Have at it. I won't be getting started for another couple of hours...

Robert Jackson

-- twitter: rwjblue
-- github: rjackson

**Comment by avdi** [comment]
I was thinking it might be nice to have this behind a dead-simple Basic Auth setup, that just used some code set in ENV to verify admin-ness. That way I could just POST some data with curl. It'd also be nice if it would just accept some raw file data instead of expecting form-encoded.

I was going to do this last night but I decided to focus on making it mountable.

**Comment by avdi** [comment]
See http://www.sinatrarb.com/faq.html#auth

**Comment by joonty** [comment]
OK great, thanks for the link. So you want that action to be left out of the github authentication and only use HTTP auth, I assume?

**Comment by rwjblue** [comment]
@avdi - Will take a look at it.  Would you want to use a single user/pass for the bulk import (meaning not database backed)?  If so we would need to use dotenv locally and heroku env vars on deploy.

**Comment by avdi** [comment]
On Thu, Jun 13, 2013 at 8:45 AM, Robert Jackson notifications@github.comwrote:

> @avdi https://github.com/avdi - Will take a look at it. Would you want
> to use a single user/pass for the bulk import (meaning not database
> backed)? If so we would need to use dotenv locally and heroku env vars on
> deploy.

Yep. Just seems like the simplest thing that could work.

What's "dotenv"? I figured we could just configure a fixed string like
"ZOMGSECRET" in dev/test mode.

**Comment by rwjblue** [comment]
See [dotenv](https://github.com/bkeepers/dotenv).  Basically, it loads ini style values from a file named `.env` and puts it into your ENV hash.  You would then add it to your `.gitignore`, and away you go.

It basically, lets you use heroku style ENV values without having to check them in or anything.

**Comment by avdi** [comment]
Neat! Thanks.

Still, in this case is there any need to have another thing to configure
locally for dev mode?

**Comment by rwjblue** [comment]
OK, will add to `application.example.yml` with a default value of 'FOOBAR' as suggested.

**Comment by avdi** [comment]
Just to clarify, it does seem like a good idea to use dotenv. It would save
a lot of mucking about with YAML.

I don't think we need to add this to the YAML at all - just do something
like:

``` ruby
configure :test, :development do
  set :default_admin_password, "XYZZY"
end
#  ...
post '/code/import' do
  admin_password = ENV.fetch('PPWM_MATCHER_ADMIN_PASS') {
settings.default_admin_password }
  # reject if there is no admin password
  # otherwise see if it matches the provided password
  # ...etc...
end
```

But I haven't tried this.

**Comment by rwjblue** [comment]
Yep, thats where I took it.  I thought the YAML was annoying...

**Comment by joonty** [comment]
Just imagine if it had been XML :disappointed_relieved:

**Comment by avdi** [comment]
On Thu, Jun 13, 2013 at 9:25 AM, Jonathan Cairns
notifications@github.comwrote:

> Just imagine if it had been XML [image: :disappointed_relieved:]

Heh :-)

## 

Avdi Grimm
http://avdi.org

I only check email twice a day. to reach me sooner, go to
http://awayfind.com/avdi

**Comment by rwjblue** [comment]
Basic auth is addressed in #17.  Working on the raw file upload now.  Are you wanting to a standard file upload (multipart post)?

**Comment by avdi** [comment]
I think ideally i'd just do:

```
curl -X POST -H 'Content-Type: text/plain' -d @codes.txt
http://pairprogramwith.me/match/codes
```

So, no form encoding at all. Just treat the raw entity body as a plain-text
list of codes, one per line.

**Comment by rwjblue** [comment]
Understood.  We are finishing #17 now to add basic auth, then I'll get this done.

**Comment by joonty** [comment]
That's a TODO then: at the moment we have to do something like:

```
curl -X POST -H 'Content-Type: text/plain' -d "codes[]=ABC123,DEF456"
```

**Comment by bf4** [comment]
re dotenv, that could make this PR easier too https://github.com/avdi/ppwm/pull/31 :)

**Comment by rwjblue** [comment]
Working on the plain file upload now...
