### ISSUE TITLE
don't let codes be re-used by other users

### ISSUE THREAD

**Issue by house9** [rubyrogues/ppwm-matcher#21]
going to have a crack at this

**Comment by rwjblue** [comment]
The models should prevent more than two users to be assigned to the same code, but there should be a unique constraint/index in the database for the code values.

**Comment by bf4** [comment]
which is also to say the TODO item in the readme is out of date

**Comment by bf4** [comment]
```
has_many :users, limit: 2 # ?
```

**Comment by rwjblue** [comment]
`has_many :users, :limit => 2` just makes sure that the association only returns two items.  The real limiting is done in `Code#cannot_have_more_than_two_users`.

**Comment by rwjblue** [comment]
Theoretically, we could also add a conditional to `Code#assign_user` but I thought it would be superfluous considering the validation...

**Comment by bf4** [comment]
tell don't validate?

**Comment by rwjblue** [comment]
Not sure how it would be more assertive.  Care to share a gist and/or code snippet with an example?

**Comment by bf4** [comment]
but seriously, this check needs to be done _after_ we validate that an email address is included, otherwise we might match to an invalid, user, no?

Also, a Code should have users, but a User don't have a code, right?

**Comment by bf4** [comment]
@rjackson was sorta joking... if you control the setter interface, you don't need a model validation.. that's all I meant

**Comment by rwjblue** [comment]
`User` does `belong_to :code`, but it isn't required (meaning :code_id can be nil for a given user).

**Comment by house9** [comment]
i think part of the problem is that the `Code` object is not changing when a User is assigned the code, so `Code` validation will not be invoked, i am adding a few specs to CodeMatcher to replicate the issue; might need minor tweaks to force update on code

![data_model](https://f.cloud.github.com/assets/52154/649233/a450e4c8-d440-11e2-8efe-02dfb5b98a60.png)

**Comment by bf4** [comment]
Thoughts: It should be user has_one :pair, through: :codes or CodeMatcher.pair_for_user(user) => returns a User or a NoUserFound which maybe a user can call, but isn't a property of the user....

**Comment by rwjblue** [comment]
@house9 - Could possibly change the association in `User` to be `belongs_to :code, :validate => true`.  This is supposed to cause the association to be validated on save...

**Comment by rwjblue** [comment]
@bf4 - Adding a `has_one` association simply adds the `#pair` method to user (along with a bunch of other stuff).  I find that defining the method directly in `User` makes it easier (and less AR magic).

Also, I'm not sure how you would exclude the current user from the association (could be missing something obvious here though)...

**Comment by house9** [comment]
this isn't looking to be too difficult, i just need to ensure the `Code` validation gets invoked and bubbled up to the UI properly

**Comment by house9** [comment]
@bf4 or @rjackson - do you want to take a look at pull request - https://github.com/rubyrogues/ppwm-matcher/pull/24 

ran into some strange issues with validations working but not rolling back the updates to `user.code_id` - initially tried using `raise ActiveRecord::Rollback` but doesn't seem to play nice with Sinatra compared to rails 

anyhow the code seems to work - just don't like the duplicated logic for checking `code.users.length` exists in the validation and in the `CodeMatcher` - the logic is slightly different but basically the same

**Comment by house9** [comment]
i went ahead and merged the code - while it could be done without conflicts

**Comment by rwjblue** [comment]
To me the best thing to do would be to take out the code validation, and leave only the `CodeMatcher` to do the checks.  Since we control that assignment we just don't call `code.users << user` or `user.code = code`.  We could even disable these methods altogether if we wanted to.

**Comment by rwjblue** [comment]
@house9 - Not to say there is anything wrong with the way you have done it here.
