### ISSUE TITLE
Should /code/create be removed or just protected?

### ISSUE THREAD

**Issue by rwjblue** [rubyrogues/ppwm-matcher#22]
It seems odd that `/code/create` is a GET request (I would usually use a POST for creation), but as I was thinking about it I don't see anywhere in the code that uses it at all.

I suggest one of the following:
1. Remove it altogether.
2. Make it `protected!` (like `/code/import`) and a POST.
3. Make it a POST, and still leave it public.

I assume we want 2. I'll put together a PR for it if others agree.

**Comment by joonty** [comment]
Nah, I put it in for testing purposes right at the beginning. Now we have bettter ways (`rake db:seed`, POST to `/code/import`).

Don't worry about the PR, I'll just delete it.

Thanks
