### ISSUE TITLE
able to create multiple User accounts (different emails) but for the same github account

### ISSUE THREAD

**Issue by house9** [rubyrogues/ppwm-matcher#25]
See screenshot below

I am guessing this is somewhat of an edge case in the real world usage of the app, but...

the same github user can create new `User` records by entering multiple email addresses

![multiple-users-same-github](https://f.cloud.github.com/assets/52154/650002/239a0d20-d452-11e2-994c-a145671087f3.png)

**Comment by house9** [comment]
maybe we should always find the user by `github_login` and then allow updates on the email of the `User` account instead of generating a new `User`

**Comment by rwjblue** [comment]
Yeah, I agree completely.  We should use `github_login` as immutable, and allow changing email if needed.

**Comment by house9** [comment]
ok - i'll start on that

**Comment by bf4** [comment]
good catch! :+1:

**Comment by house9** [comment]
@rjackson or @bf4  - do you want to review this commit? - https://github.com/rubyrogues/ppwm-matcher/pull/27 

I am going to grab some lunch - so merge it if you want, or i can in bit

**Comment by house9** [comment]
closing - this fix has been merged
