### ISSUE TITLE
Denied page renders broken image in production [LOW priority]

### ISSUE THREAD

**Issue by house9** [rubyrogues/ppwm-matcher#36]
See screenshot below: comparison of development vs production when accessing a protected page
- access site via github login
- try to access a protected page when not a site admin
- results in broken image display

![denied](https://f.cloud.github.com/assets/52154/652628/49275afa-d4b3-11e2-81a4-96aa98a0c673.png)

**Comment by rwjblue** [comment]
Looks like this is being done from sinatra_github_auth [here](https://github.com/atmos/sinatra_auth_github/blob/master/lib/sinatra/auth/github.rb#L14).  

We can override. I'm working on a PR to fix...
