### ISSUE TITLE
Letting you know when your 'pair' signed in

### ISSUE THREAD

**Issue by joonty** [rubyrogues/ppwm-matcher#37]
I'm happy to pick this one up.

The idea would be that when the second of the pair signs up, it finds the first pair and emails them with the second pair's details and a link back to `/match/code`.

I'll submit it as a PR, and if anyone has any better ideas in the meantime just let me know.

**Comment by rwjblue** [comment]
I think it should probably email both users (not just the first one) with the full details.  So basically, the same email body is sent to both of them (which would include both email addresses, the code, and possibly the time signed up).

Is that what you were thinking?

Are you going to be using ActionMailer?

**Comment by joonty** [comment]
@rjackson do you ever sleep? :-P

Yes, I was thinking both users, despite the fact I didn't mention it in my post...

I wasn't thinking of ActionMailer, I thought I'd go with something light-weight like 
[pony](https://github.com/benprew/pony). However, that's definitely open to discussion.

What would you say is the best way to supply configuration parameters? `application.yml`?

**Comment by rwjblue** [comment]
pony looks cool, haven't used it before.  (also I keep forgetting that this is sinatra not rails...)

Heroku has a sendgrid addon (see [here](https://devcenter.heroku.com/articles/sendgrid)). They also give an example template for using pony with the addon:

``` ruby
Pony.options = {
  :via => :smtp,
  :via_options => {
    :address => 'smtp.sendgrid.net',
    :port => '587',
    :domain => 'heroku.com',
    :user_name => ENV['SENDGRID_USERNAME'],
    :password => ENV['SENDGRID_PASSWORD'],
    :authentication => :plain,
    :enable_starttls_auto => true
  }
}
```

**Comment by rwjblue** [comment]
You could use [mailcatcher](https://github.com/sj26/mailcatcher) for easy testing in development/test.

I would think you would just use two different configure blocks in the sinatra app to use different options for both envs:

``` ruby
configure :test, :development do
  Pony.options = {:via => :smtp, :via_options => {:address => 'localhost', :port => '1025'}}
end

configure :production do
  Pony.options = {
    :via => :smtp,
    :via_options => {
      :address => 'smtp.sendgrid.net',
      :port => '587',
      :domain => 'heroku.com',
      :user_name => ENV['SENDGRID_USERNAME'],
      :password => ENV['SENDGRID_PASSWORD'],
      :authentication => :plain,
      :enable_starttls_auto => true
    }
  } 
end
```

Make sense?

**Comment by joonty** [comment]
Do we know whether @avdi wants to use sendgrid? It does mean money.

Good shout on mailcatcher though, I've been looking for something like that.

**Comment by rwjblue** [comment]
The heroku addon for sendgrid has a free tier with a limit of 6000 per month (which I think should be enough for now).

Links:

https://devcenter.heroku.com/articles/sendgrid
https://addons.heroku.com/sendgrid

**Comment by joonty** [comment]
Ah fine, thanks for that.

**Comment by rwjblue** [comment]
Hey, you're doing all the hard work here :)

I'm just slinging links around...

**Comment by avdi** [comment]
FWIW Pony/Sendgrid sounds great (I've used Pony on other projects), and I
love this idea!

**Comment by rwjblue** [comment]
@joonty - How's it going on this? I am free to pair for a bit on it if you'd like...

**Comment by joonty** [comment]
Hi, I was dragged on to another project earlier unfortunately, but I'm back on it :)

@rjackson I've almost finished actually, but thanks for the offer!

**Comment by joonty** [comment]
See PR #40.
