### ISSUE TITLE
Getting emails from unknown ponies, and reply-to?

### ISSUE THREAD

**Issue by joonty** [rubyrogues/ppwm-matcher#44]
The emails are working - @rjackson and I have tested and confirmed it on production.

However, the email comes from _pony@unknown_. Personally, that makes me chuckle. On the other hand, it might be better to have an email from the pairprogramwith.me domain.

@avdi what address should we use?

Another nice feature would be a reply-to that goes to the user's pair.

**Comment by rwjblue** [comment]
It doesn't seem to be validated so we can probably use 'matcher@pairprogramwith.me' for now.

I'm not sure how the reply-to would work. The 'natural' assumption to replying is that you are responding to who sent you the email (in this case our app).

**Comment by rwjblue** [comment]
I'm working on a PR for #43 (save users name), so I'll add the from address while I'm in there...

**Comment by avdi** [comment]
On Fri, Jun 14, 2013 at 11:51 AM, Robert Jackson
notifications@github.comwrote:

> It doesn't seem to be validated so we can probably use '
> matcher@pairprogramwith.me' for now.
> 
> Seems reasonable. When I have some time I can make that a real address.
> 
> I'm not sure how the reply-to would work. The 'natural' assumption to
> replying is that you are responding to who sent you the email (in this case
> our app).

Having the reply-to go to the other pair actually sounds kinda cool, though
I agree it's a little non-obvious. Maybe include a note in the email saying
that replies will go to the other person?

**Comment by rwjblue** [comment]
Will do.  Finishing PR now.

**Comment by joonty** [comment]
Great! Sadly that's all from me for the day.

@avdi the reply-to would just be an addition, so users could either grab the pair's email from the body or just click reply. But it's not important in the grand scheme of things. 

You said you needed the app by today, so does that mean you're talking at a conference today? If so, all the best.

**Comment by rwjblue** [comment]
@joonty - Great work today!

**Comment by avdi** [comment]
On Fri, Jun 14, 2013 at 12:06 PM, Jonathan Cairns
notifications@github.comwrote:

> You said you needed the app by today, so does that mean you're talking at
> a conference today? If so, all the best.

Tomorrow. And thank you! Later today I'll be loading up the site with my
list of "real" codes, and I plan on passing around a basket of cards that I
printed up during my talk. I'm so excited!!

**Comment by rwjblue** [comment]
Not sure if you saw, but the from and reply_to are now set as discussed. 

@avdi - Let me/us know if you have any issues crop up while doing the import or pre-flight testing...
