### ISSUE TITLE
require an email address if not submitted

### ISSUE THREAD

**Issue by house9** [rubyrogues/ppwm-matcher#9]
i have some 'working' code to handle this - will submit shortly

**Comment by house9** [comment]
@bf4 - want to take a look at this commit? - https://github.com/house9/ppwm-matcher/commit/e85830fc82c04b3499bf303b9bbcb81cfebce4bf 

moves code out of app.rb into new class - not sure if this is a direction we want to go?

requires a merge of #8 before I put in a pull request

**Comment by rwjblue** [comment]
Assuming this is the direction to go is there any way for you to add specs for `CodeMatcher`?

**Comment by house9** [comment]
yeah - i'll put some together

**Comment by house9** [comment]
@rjackson - specs added on the pull request - https://github.com/rubyrogues/ppwm-matcher/pull/13

**Comment by joonty** [comment]
Now in #14.

**Comment by joonty** [comment]
This is now working and in `master`, closing.
